package com.dh.cardsservice.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "cards")
public class Card {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(description = "id of my card, usually generated by the database")
    private Long id;
    @NotNull
    @Size(min = 1, max = 250)
    private String type;
    @NotNull
    private Double balance;
    @NotNull
    @Schema(description = "id of account that i want to  associate to  mi card")
    @Column(name = "account_id")
    private Long accountId;
    @NotNull
    @Column(name = "card_number")
    @Schema(description = "my card number cant be duplicate that means the card its already associated with mi account o with other one")
    private String cardNumber;
    @NotNull
    @Size(min = 1, max = 250)
    @Column(name = "account_holder")
    private String accountHolder;
    @NotNull
    @Column(name = "expire_date")
    private LocalDateTime expireDate;
    @NotNull
    @Size(min = 1, max = 250)
    @Column(name = "bank_entity")
    private String bankEntity;
}
