DROP DATABASE IF EXISTS digitalmoney;
CREATE DATABASE digitalmoney;
USE digitalmoney;
CREATE TABLE users (
id INT AUTO_INCREMENT NOT NULL,
name VARCHAR(250) NOT NULL,
last_name  VARCHAR(250) NOT NULL,
dni INT NOT NULL,
email VARCHAR(250) NOT NULL,
phone  BIGINT NOT NULL,
password TEXT(1000) NOT NULL,
cvu BIGINT NOT NULL UNIQUE,
alias VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);