package com.dh.userservice.entities;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "information required only for mapping my user entity")
public class AppUserDTO {
    @Schema(description = "id of my userAccount, usually generated by the database")
    private Long id;
    @NotNull
    @Size(min = 1, max = 250)
    private String first_name ;
    @NotNull
    @Size(min = 1, max = 250)
    private String last_name ;
    @NotNull
    @Size(min = 1, max = 250)
    private String dni ;
    @NotNull
    @Size(min = 1, max = 250)
    @Schema(description = "email of mi user cant be used in other accounts")
    private String email ;
    @NotNull
    @Size(min = 1, max = 250)
    private String phone ;
    @NotNull
    @Size(min = 1, max = 250)
    private String password;


}
