package com.dh.accountservice.entities;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;
import java.util.Set;
@Entity
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "accounts")
@Schema(description = "Complete parameters to create my userAccount entity")

public class Account {
    @Id
    @Schema(description = "id of my userAccount, usually generated by the database")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column
    @Schema(description = "alias of my user account, it is generated on a txt taking random words")
    @Size(min = 1, max = 250)
    private String alias;
    @Column
    @NotNull
    @Size(min = 22, max = 22)
    private String cvu;
    @Column
    @NotNull
    private Double balance;
    @Column
    @Schema(description = "id of my user, has to be related with my account")
    @NotNull
    private Long user_id;
    @Transient
    private List<Transaction> transactions;
    @Transient
    private Set<Card> cards;
}
