package com.dh.accountservice.entities;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AccountDTO {
    @Schema(description = "id of my userAccount, usually generated by the database")
    @NotNull
    private Long id;
    @Schema(description = "alias of my user account, it is generated on a txt taking random words")
    @Size(min = 1, max = 250)
    private String alias;
    @NotNull
    @Size(min = 22, max = 22)
    private String cvu;
    @NotNull
    private Double balance;
    @Schema(description = "id of my user, has to be related with my account")
    @NotNull
    private Long user_id;
}
