package com.dh.accountservice.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AccountCreateRequestDTO {
    @Schema(description = "id of my userAccount, usually generated by the database")
    private Long id;
    @NotNull
    @Size(min = 22, max = 22)
    private String cvu;
    @Schema(description = "id of my user, has to be related with my account")
    @NotNull
    private Long user_id;
}
