package com.dh.accountservice.entities;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Card {
    @Schema(description = "id of my Card, usually generated by the database")
    private Long id;
    @Size(min = 1, max = 250)
    @NotNull
    private String type;
    @NotNull
    private Double balance;
    @Schema(description = "id of my account, has to be related with my card")
    @NotNull
    private Long accountId;
    @Size(min = 13, max = 18)
    @NotNull
    private String cardNumber;
    @Size(min = 1, max = 250)
    @NotNull
    private String accountHolder;
    @NotNull
    private LocalDateTime expireDate;
    @Size(min = 1, max = 250)
    @NotNull
    private String bankEntity;
}
